apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: sealed-test-secret
  namespace: default
spec:
  encryptedData:
    PASSWORD: AgDFxoldVZ+ZBnZTwdbwa1NGEJzwVIhIdvGVM3+49Svkk+q2ArR3fmeJkzwXDvhCQCd5kNjrmF1lBNpBlpgFHs3hCptE0Sjp0nm+ZuMQLPMzRylteEqHSFRk/ylQ3X0jyT7gQYsKPewLLrksYzrIG7WT9Ntxwj5NGokbzokqdMTHfPbwLD7WHbUzwjMOYC/MFATY8LzgM6Ea2uN3lbIdfbVamMYUgXraJygCiywKbCd0nqNkOqNpK/CRRS62FqwgknlP71RuENBGHAkKV3Fz4T04y8sx+zM5vksdRmOEbOElCSvQKPO3Rjyg+DcqUhRlRDL7FAaX7WmN1DyTg1Gqw7kYnBd6eD6hKO8CO4aXaDe/oV1kp7C8HlsOUxLG5cFZuuBFkyqLa9HoYYMXl4qXDMQMhWtDgAGIDUE3UzdE2+lRElvPGBdvM77sIo0JndvCEK2WoBD4kxe5aVUcLe3F9B2ZIfgh0KysAhZxjxoC4QHdsctGQBAtwgtnAEzcGnN70djz8NG4EaqbcjqoblFgnfDv400A7EbQh8lYzO8x4MJM6UZ0sVsggzUTq5qdxZUlbaao7cBBnP2gPP09nFRviBV15405nUsYzGqD1CZCs0Ziol3sxm91Qxo/I4rkhaOyNRsScogyx6hFjovdKs2yMA5K40D7G79+4YjciUiLcYevqFVEjn/xZ6OHEeXQp3MQlsQCOWmNosv8gQ==
  template:
    metadata:
      creationTimestamp: null
      name: sealed-test-secret
      namespace: default
                        
